version: '3'
services:
  module3:
    image: module3:latest
    container_name: module3
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
    networks:
      - mongo_network
networks:
  mongo_network:
    name: mongo_default
    external: true
